[general]
touch = true
# Use 1080p as the base for the 1920 width
resolution = 1280x720
# Set total margin height to 360 (1080 - 720 = 360) to get 720 height
marginheight = 280
marginwidth = 0
# cropmargins=true resizes the window to 1920x720 instead of showing black bars
cropmargins = true
dpi = 160
framerate = 60

[sensors]
location = true
night_mode = true
driving_status = true